# Generated by Django 4.0 on 2021-12-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image_url', models.URLField(help_text='The URL to the image file itself', max_length=255, verbose_name='Image URL')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
